### ISSUE TITLE
iFrame support

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#108]
Use-case from @fideltian: The Zoom SDK is commonly used in iframes so we need to investigate if/how we can support the feature in iframes and what it means for privacy

@anssiko

**Comment by anssiko** [comment]
One possible solution is to use the [allow attribute of the iframe element](https://w3c.github.io/webappsec-permissions-policy/#iframe-allow-attribute).

This would require 3rd party developers integrating Zoom SDK via an iframe to update their HTML slightly and add the `allow` attribute to make use of the Compute Pressure API. I believe this is the most architecturally clean way to solve this issue.

`<iframe src="https://example.org/app" allow="foobar"></iframe>`

If the `allow` attribute is not defined, all the things would work except the Compute Pressure API would not be enabled.

@fideltian your thoughts?

**Comment by kenchris** [comment]
@anssiko do you know of any spec that does this that I can refer to for spec text?

**Comment by kenchris** [comment]
OK I assume this is what I need: https://www.w3.org/TR/screen-wake-lock/#policy-control

**Comment by anssiko** [comment]
> @anssiko do you know of any spec that does this that I can refer to for spec text?

The list of [Policy Controlled Features](https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md) is probably the best resource.

**Comment by kenchris** [comment]
I have run into some challenges while trying to support this.

First of all, the permission policy doesn't support workers yet and it shouldn't be inherited from the creator document of the worker according to discussions: https://github.com/w3c/webappsec-permissions-policy/issues/207

Secondly, we say that top level docs should be focused (focusable area) and workers should have a focused document in their ownet set. This is much harder to spec

**Comment by kenchris** [comment]
Iframes should work now, thought we probably need a policy for the workers but that is not yet supported so filed #110
