### ISSUE TITLE
No indication of max amount of thresholds available per metrics.

### ISSUE THREAD

**Issue by arskama** [WICG/compute-pressure#11]
There is no way we know what are the amount of thresholds for each metric.
For example at the moment, it s 1 for CPU speed (2 buckets) and 3 for CPU Utilization (4 buckets)

Should there be a getMaxThreshold() per metric? or a mechanism to tell that the amount of thresholds provided is not suitable?

**Comment by kenchris** [comment]
This was supposed to be implementation dependent - ie. up to the User Agent
