### ISSUE TITLE
Observer first update

### ISSUE THREAD

**Issue by arskama** [WICG/compute-pressure#121]
I m not sure we are clear in the specs about WHEN should happen the first update.

In the current Chrome implementation (under dev). The first registered observer will get an update, since the platform collector will send the first update after the first probing.

For the other observers, from the same page, if the state from the same source is not changing, it will never get a first update, because it will be blocked from the platform collector.

So either we let the new observer having no update until the next state change is happening, or we should send to the new observer, the latest change recorded by the already registered observers.

**Comment by kenchris** [comment]
We alrady discussed this before.

The platform collector doesn't do the filtering. It is spec'ed pretty clearly:

https://wicg.github.io/compute-pressure/#ref-for-dfn-has-change-in-data-1 <- data delivery from platform collector

Step. 5 is where it goes over each observer object.

As part of that the https://wicg.github.io/compute-pressure/#dfn-has-change-in-data test is being performed. That happens per observer object and not in the platform collector.

Now, you can implement optimizations, as long as you ensure this same behavior, such as storing the last state in the platform collector and immediately delivering that when someone connects, but you need to make sure to update timestamp etc.
