### ISSUE TITLE
Handling of empty PressureObserverOptions is unclear

### ISSUE THREAD

**Issue by rakuco** [WICG/compute-pressure#124]
https://wicg.github.io/compute-pressure/#the-constructor-method just says the [[Options]] internal slot is set to the optional `options` parameter passed in the constructor.

After that, [[Options]].samplerate is referenced in https://wicg.github.io/compute-pressure/#dfn-passes-rate-test

The spec does not seem to handle cases where `options` is not passed to the constructor or where the `samplerate` field is simply unset or 0 (in which case one of the steps in "passes rate test" even causes a division by zero).

**Comment by kenchris** [comment]
It's [constructor](https://wicg.github.io/compute-pressure/#dom-pressureobserver-constructor)([PressureUpdateCallback](https://wicg.github.io/compute-pressure/#dom-pressureupdatecallback) callback, optional [PressureObserverOptions](https://wicg.github.io/compute-pressure/#dom-pressureobserveroptions) options = {});

So in that case its {}. But we don't check what people pass in is actually an object in

https://wicg.github.io/compute-pressure/#the-constructor-method
1. Set this.[[[Options]]](https://wicg.github.io/compute-pressure/#dfn-options) to options.

So that should definitely be fixed. If sampleRate is not existing on the object we should use the value 1. I am not sure whether it makes sense setting sampleRate to 1 in the ctor if not set, or just use the value one in the https://wicg.github.io/compute-pressure/#dfn-passes-rate-test if it doesn't exist

**Comment by kenchris** [comment]
Other question comes to mind. Do people want to change the sampleRate at runtime? like call unobserve and then observe with a new value? In that case we should move it to the callback

**Comment by arskama** [comment]
> Other question comes to mind. Do people want to change the sampleRate at runtime? like call unobserve and then observe with a new value? In that case we should move it to the callback

if you call unobserve on a single source, you ll destroy the observer, so actually it doesn't cost anything to call again the constructor with new options.

To me, setting the sampleRate to 1 is fine if not defined.

**Comment by rakuco** [comment]
> or where the `samplerate` field is simply unset or 0 (in which case one of the steps in "passes rate test" even causes a division by zero).

Isn't this still an issue? It looks like the spec still allows me to pass 0 to `sampleRate` and trigger a division by zero in https://wicg.github.io/compute-pressure/#dfn-passes-rate-test

**Comment by kenchris** [comment]
Good point. We should validate the values, I need to check what other specs using sampleRate are doing to be consistent

**Comment by kenchris** [comment]
I was wondering whether I should check if sampleRate is actually a number, like done in WebIDL and at least one place in the HTML spec:

![image](https://user-images.githubusercontent.com/1101339/191466791-a06d0e6e-0761-419e-a02c-08942a3b420f.png)

But I also see that even Generic Sensors API doesn't do that at all

![image](https://user-images.githubusercontent.com/1101339/191466691-d7523e40-df50-4965-b67c-a4e487c43fe6.png)

**Comment by rakuco** [comment]
> I was wondering whether I should check if sampleRate is actually a number, like done in WebIDL and at least one place in the HTML spec:

I don't think you need to do it, you only have one type and the `Type()` call is an ECMAScript thing anyway. If `options["sampleRate"]` exists, its type is the one from the declaration (double). Some implicit conversion might happen in the IDL->JS layer, but that should be irrelevant in this case.

How about this:

```webidl
dictionary PressureObserverOptions {
  double sampleRate = 1.0;
};
```

and then something like this:

> The new PressureObserver(callback, options) constructor steps are:
> 1. Set this.[[Callback]] to callback.
> 1. If options["sampleRate"] is less than or equal to 0, throw a RangeError.
> 1. Set this.[[SampleRate]] to options["sampleRate"].

You don't need to check if `options` is a dictionary because even if it's not passed it will default to an empty one, and if you set a default value for `sampleRate` you don't need to check that it exists. You might need to use a different check than "less than or equal to" because `sampleRate` is a double though.

> But I also see that even Generic Sensors API doesn't do that at all
> 
> ![image](https://user-images.githubusercontent.com/1101339/191466691-d7523e40-df50-4965-b67c-a4e487c43fe6.png)
> 
> Why is that @rakuco - is it because you accept strings like "1.0" that will be auto converted into a number?

Strings do end up converted to a double in this case (via https://webidl.spec.whatwg.org/#es-dictionary), but in any case I've sent w3c/sensors#439 to improve the check a bit.

> Also how would we do error handling... TypeError with wrong type? NotSupportedError with negative values and 0?

https://fetch.spec.whatwg.org/#responseinit throws a `RangeError` for the "status" field, for example.

**Comment by kenchris** [comment]
> You don't need to check if options is a dictionary because even if it's not passed it will default to an empty one,

but I might call new PressureObserver(callback, true) and in that case it should fail in my opinion.

**Comment by rakuco** [comment]
> but I might call new PressureObserver(callback, true) and in that case it should fail in my opinion

It does. Per https://webidl.spec.whatwg.org/#es-dictionary:
> If [Type](https://tc39.es/ecma262/#sec-ecmascript-data-types-and-values)(esDict) is not Undefined, Null or Object, then [throw](https://webidl.spec.whatwg.org/#ecmascript-throw) a [TypeError](https://tc39.es/ecma262/#sec-native-error-types-used-in-this-standard-typeerror).

**Comment by kenchris** [comment]
Right, I did see other specs check whether it was a dictionary though. E.g. https://dom.spec.whatwg.org/#dom-document-createelement

**Comment by kenchris** [comment]
> It does. Per https://webidl.spec.whatwg.org/#es-dictionary:

Also when it is optional?

**Comment by rakuco** [comment]
> Right, I did see other specs check whether it was a dictionary though. E.g. https://dom.spec.whatwg.org/#dom-document-createelement

That's because of createElement's (abbreviated) signature is

```webidl
Element createElement(DOMString localName, optional (DOMString or ElementCreationOptions) options = {});
```

so `options` is a union and you need to check if it's a dictionary or a DOMString.

>> It does. Per https://webidl.spec.whatwg.org/#es-dictionary:
>
> Also when it is optional?

If we have `constructor(optional PressureObserverOptions options)` without a default value, you essentially have `constructor()` and `constructor(PressureObserverOptions options)`. The conversion in https://webidl.spec.whatwg.org/#es-dictionary would happen on either an object or `undefined` (and the values of each member would depend on whether they're required, have a default etc).

**Comment by rakuco** [comment]
> > You don't need to check if options is a dictionary because even if it's not passed it will default to an empty one,
> 
> but I might call new PressureObserver(callback, true) and in that case it should fail in my opinion, or at least sampleRate should be set to 1 :-)
> 
> Actually that is for future proofing, you might think that is a bad thing to call and it should fail, but most APIs taking options are designed to not throw in that case as we have the ability to add overloads to the method in the future like
> 
> PressureObserver(Callback, OtherCallback, Options)

That would depend on what the overloads would look like (in terms of number of required/optional arguments, their types etc), the rules in https://webidl.spec.whatwg.org/#idl-overloading are quite long so it's hard to give a definitive answer.

**Comment by kenchris** [comment]
Yeah, I got it now, I will follow your suggestion.

**Comment by rakuco** [comment]
Glad to see that it worked :-)

Just one thing I mentioned above:

> You might need to use a different check than "less than or equal to" because `sampleRate` is a double though.

I'd double check (pun unintended) that, doing comparisons with floating-point numbers is always tricky, and I don't know how that's usually done in spec land.

**Comment by kenchris** [comment]
> I'd double check (pun unintended) that, doing comparisons with floating-point numbers is always tricky, and I don't know how that's usually done in spec land.

I know that, and I tried to find existing examples but so far without success
