### ISSUE TITLE
Should `factors` in Data Delivery be a list?

### ISSUE THREAD

**Issue by rakuco** [WICG/compute-pressure#131]
In https://wicg.github.io/compute-pressure/#dfn-data-delivery:

> Let factors be an [implementation-defined](https://infra.spec.whatwg.org/#implementation-defined) [sequence](https://webidl.spec.whatwg.org/#idl-sequence) given data and source, potentially [empty](https://infra.spec.whatwg.org/#list-empty).

I find it odd that `factors` is supposed to be a sequence, which is a Web IDL construct, rather than something defined in the Infra spec, like a list.

**Comment by kenchris** [comment]
Let's change it to a list then

**Comment by rakuco** [comment]
Don't forget you'll probably need to expand https://wicg.github.io/compute-pressure/#dfn-has-change-in-data to compare record["factors"] and `factors`.

**Comment by rakuco** [comment]
Actually, doesn't it make more sense for it to be a [set](https://infra.spec.whatwg.org/#sets)? I don't see why ["thermal", "thermal"] should be allowed, for example.

**Comment by kenchris** [comment]
Probably should be, but how does that get exposed to JS devs? as an actual Set object?

**Comment by rakuco** [comment]
I'm referring to `factors` as the data you get from the platform side and which is not exposed to developers. Not to be confused with `PressureRecord["factors"]`, which is exposed to developers and which is initialized from `factors` in https://wicg.github.io/compute-pressure/#dfn-create-a-record (not sure if the wording there needs to be expanded to cover this conversion btw).

**Comment by kenchris** [comment]
I did a PR, not sure if this is the best way to spec this
