### ISSUE TITLE
`factors` handling in "Has change in data" in unclear

### ISSUE THREAD

**Issue by rakuco** [WICG/compute-pressure#132]
https://wicg.github.io/compute-pressure/#dfn-has-change-in-data has:

> If record.[factors](https://wicg.github.io/compute-pressure/#dom-pressurerecord-factors) and factors does not [contain](https://infra.spec.whatwg.org/#list-contain) the same [items](https://infra.spec.whatwg.org/#list-item), return true.

* ~What does _"If record.factors"_ mean? Is it _"If record["factors"] exists"_?~
  * edit: The sentence is supposed to be "If record.factors and factors DO not contain [...]", "If record.factors" is not being used as a boolean check.
* I _think_ that using [contain](https://infra.spec.whatwg.org/#list-contain) like that does not work (even after `factors` is changed into an Infra list type), as it checks if a specific item is in the list. Don't you need to be more verbose there to compare the list and the sequence?

**Comment by kenchris** [comment]
I think I copied this wording from elsewhere.

It is basically if both "sets" contains the same items (order doesn't matter). An implementation can of course order the items and compare one by one, and do optimizations like checking if length is equal first, but I think we want to leave such optimizations up to implemetnation

**Comment by rakuco** [comment]
> It is basically if both "sets" contains the same items (order doesn't matter).

I figured that was probably the intention, but the spec text does not completely match the idea. `record["factors"]` is a sequence<T>, which is basically a list, which means it is allowed to have duplicate items and that items are stored in a certain order. "If listA and listB do not contain the same items" is kind of hand-wavy, as "contains" is defined only for checking if a single item is in a list. Since the spec is talking about lists, it's hard to deviate from iterating and checking for equality of the items in the same order, but even that is not clear from the text.

Another possibility would be making `factors` an Infra [set](https://infra.spec.whatwg.org/#sets) and comparing that to another set instead of records["factors"] (e.g. something like "setA is a superset and a subset of setB" maybe?)

**Comment by rakuco** [comment]
> * What does _"If record.factors"_ mean? Is it _"If record["factors"] exists"_?

Going back to this specifically: I think I understood the text now, the "does" instead of "do" there confused me. It's _"If record["factors"] and factors do not contain the same items"_ AFAICS. I've edited the issue description and struck this part of the text.
