### ISSUE TITLE
Use dictionary notation when referring to PressureRecord members

### ISSUE THREAD

**Issue by rakuco** [WICG/compute-pressure#133]
PressureRecord is a [dictionary](https://webidl.spec.whatwg.org/#idl-dictionaries), which is basically an [ordered map](https://infra.spec.whatwg.org/#ordered-map).

As such, I'd expect the spec to refer to its members using the ordered map notation (`foo["bar"] instead of foo.bar`).

**Comment by kenchris** [comment]
Please have a look @rakuco
