### ISSUE TITLE
Check permissions policy in constructor() method instand of observe() method

### ISSUE THREAD

**Issue by wangw-1991** [WICG/compute-pressure#144]
In current spec, permissions policy is checked in observe() method. As a result, we can construct a PressureObserver instance and call all other methods except observe() even if Compute Pressure is not allowed by permissions policy. Is this what we expected?

If we check permissions policy in constructor() method, then we can't construct a PressureObserver instance when Compute Pressure is not allowed by permissions policy. All the methods can't be called too.

**Comment by kenchris** [comment]
But we need to make sure we are consistent with other APIs, for instance, I believe WakeLock checks in the request() method. Wei can you check if existing *Observer APIs use permission policy and where they make the checks?

**Comment by rakuco** [comment]
By the way, what I usually do to find out which Observer APIs there are in the first place is to call `git grep Observer -- \*.idl` from Blink, then look at the comments with the spec URLs. Of course you can also just check the Blink implementations, but they might not always match the spec.

**Comment by wangw-1991** [comment]
Thanks Kenneth and Raphael. I don't find any other *Observer interfaces that check permissions policy in the constructor. So do we still need to change the spec or keep it unchanged to be consistent with other APIs?

**Comment by kenchris** [comment]
I would opt for consistency with existing APIs unless there is a strong compelling reason not to. In that case, we should probably consult the W3C TAG for advice

**Comment by rakuco** [comment]
Looking at the specs here, it looks like the other Observer APIs don't do any permissions policy checks at all, so we're kind of in uncharted territory here :-)

Usage in other APIs varies. Web Share does checks on multiple operations, others do it in specific methods (but often have only one exposed method :-)

One argument in favor of doing it in observe() is that it's the operation that is expensive and triggers all the machinery on the platform side, so calling e.g. disconnect() or takeRecords() without calling observe() first is essentially a NOP.

**Comment by wangw-1991** [comment]
To keep consistent with existing APIs, we still do permissions policy check in observer() method and no need to change the spec.

The CL is already merged (https://chromium-review.googlesource.com/c/chromium/src/+/3963324), so close this issue.
