### ISSUE TITLE
Allow the API to work in the background (with limitations)

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#16]
Broken out from https://github.com/WICG/compute-pressure/issues/14

From Zoom:
> we would like the api could be workable even if the tab is inactive or minimized. We have a use case about desktop sharing.

This of course affects privacy so we will see if we need to add certain restrictions in order to make this work., like we could make it work only for focused tabs (like currently implemented, I believe) but allow it also when a tab is currently sharing content using the APIs allowing for that.

**Comment by fideltian** [comment]
besides sharing, maybe PIP as well.

**Comment by kenchris** [comment]
> besides sharing, maybe media capture(audio/video) and PIP as well.

Yes, that makes sense. Maybe @beaufortfrancois knows other similar cases where this might make sense
