### ISSUE TITLE
Handle removing promises from pendingObservePromises list

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#168]
Handle removing promises from pendingObservePromises list when promises settle. The current text is too hand-wavy from an implementation perspective so more clarity will be needed.

WebHID does it partially: https://wicg.github.io/webhid/#dfn-pendingsendreportpromises is emptied in https://wicg.github.io/webhid/#ref-for-dfn-pendingsendreportpromises-2 and https://wicg.github.io/webhid/#ref-for-dfn-pendingsendreportpromises-4 but not in the success case.

Web Bluetooth seems to handle it a bit better: https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetooth-attributeinstancemap-slot

**Comment by rakuco** [comment]
Isn't this covered by the "React to Promise" excerpt in the latest version of #167?

**Comment by kenchris** [comment]
It is indeed!
