### ISSUE TITLE
Don't call callback if values didn't change

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#17]
Broken out from https://github.com/WICG/compute-pressure/issues/14

> The observer mode will return the cpuUtilizationThresholds every 1 second. how about returning only when there is change. otherwise the callback is too often.

This should be an easy change and one that I agree with.

**Comment by kenchris** [comment]
@arskama do you think we can chose this one?

**Comment by arskama** [comment]
Specs have a been changed in patch 
https://github.com/WICG/compute-pressure/pull/18

There is an implementation patch pending review.
https://chromium-review.googlesource.com/c/chromium/src/+/3383804

**Comment by arskama** [comment]
closing.
In specs and implemented also.
