### ISSUE TITLE
How do you handle multiple ComputePressureObserver?

### ISSUE THREAD

**Issue by npm1** [WICG/compute-pressure#2]
The API is very clear that a (main) frame is only allow to specify one set of buckets. How is the API going to enforce this? With the current example, it sounds like I could create multiple observers and hence get arbitrary precision on the values exposed.

**Comment by pwnall** [comment]
Here is a proposal

1. For every origin with live ComputePressureObservers, the user agent stores (in RAM, no persistence needed) the quantizing scheme (list of buckets).
2. When a new ComputePressureObserver instance is created, its quantizing scheme is compared against the stored scheme.
    a. If no scheme is stored, store the current scheme.
    b. If the scheme matches the stored scheme, proceed.
    c. If the scheme does not match the stored scheme, stop/cancel all existing observers. This should entail sending some error event.
3. A newly created ComputePressureObserver only becomes eligible for receiving change events after the check above. (after the 1 or 10-second delay)
4. When all the ComputePressureObservers for an origin are removed, the stored scheme is cleared as well.

The main alternative I've considered is failing ComputePressureObserver creation if the current scheme doesn't match the stored scheme. I dislike that this alternative can "wedge" an origin that's trying to push updated code.

**Comment by npm1** [comment]
> Here is a proposal
> 
> 1. For every origin with live ComputePressureObservers, the user agent stores (in RAM, no persistence needed) the quantizing scheme (list of buckets).

Why is no persistence needed? This should persist until all pages in the origin are unloaded right? Otherwise this seems to imply that the bucketing can change based on GC timings in the browser, which has no use case and seems like it would be confusing to developers.

> 2. When a new ComputePressureObserver instance is created, its quantizing scheme is compared against the stored scheme.
>    a. If no scheme is stored, store the current scheme.
>    b. If the scheme matches the stored scheme, proceed.
>    c. If the scheme does not match the stored scheme, stop/cancel all existing observers. This should entail sending some error event.

Unclear to me why you cancel all existing observers. Do you want to cancel even the ones that were using a valid bucketing scheme?

> 3. A newly created ComputePressureObserver only becomes eligible for receiving change events after the check above. (after the 1 or 10-second delay)

The delay seems good, also kinda necessary to prevent quick fingerprinting via JS routing (load an origin, use the API using some buckets, use JS to redirect to a different origin that's also under your control, and now you can use different buckets).

> 4. When all the ComputePressureObservers for an origin are removed, the stored scheme is cleared as well.

Perhaps I'm not sure what you mean by removed, but I don't think this will work because then an attacker could create an observer, observe, remove, and then create another observer with a different scheme.

> 
> The main alternative I've considered is failing ComputePressureObserver creation if the current scheme doesn't match the stored scheme. I dislike that this alternative can "wedge" an origin that's trying to push updated code.

Oh so I guess this is why you'd want to stop/cancel all observers? I still don't think this is good enough for privacy due to my answer to 4).

**Comment by pwnall** [comment]
> > Here is a proposal
> > 
> > 1. For every origin with live ComputePressureObservers, the user agent stores (in RAM, no persistence needed) the quantizing scheme (list of buckets).
> 
> Why is no persistence needed? This should persist until all pages in the origin are unloaded right? Otherwise this seems to imply that the bucketing can change based on GC timings in the browser, which has no use case and seems like it would be confusing to developers.

Sorry, maybe I'm using the wrong word here. I meant "persistence" in the sense of state that persists across browsing sessions, like in https://w3ctag.github.io/security-questionnaire/#persistent-origin-specific-state

Maybe a better conceptual model is that the user agent stores a list of ComputePressureObservers for each origin, and compares requests against the quantizing scheme in the first observer in the list.

My idea has a rep invariant that I wasn't explicit about -- all active ComputePressureObservers for an origin have the same quantizing scheme. I think this matches the security & privacy objective we're trying to achieve, namely that an origin can't get events corresponding to multiple quantizing schemes.

> 
> > 1. When a new ComputePressureObserver instance is created, its quantizing scheme is compared against the stored scheme.
> >    a. If no scheme is stored, store the current scheme.
> >    b. If the scheme matches the stored scheme, proceed.
> >    c. If the scheme does not match the stored scheme, stop/cancel all existing observers. This should entail sending some error event.
> 
> Unclear to me why you cancel all existing observers. Do you want to cancel even the ones that were using a valid bucketing scheme?

All existing observes must have matched the stored bucketing scheme. This means that (1) all existing observers have the same bucketing scheme, and (2) this bucketing scheme conflicts with the new observer's bucketing scheme. In other words, all existing observers conflict with this new observer, and therefore must be canceled.

> 
> > 1. A newly created ComputePressureObserver only becomes eligible for receiving change events after the check above. (after the 1 or 10-second delay)
> 
> The delay seems good, also kinda necessary to prevent quick fingerprinting via JS routing (load an origin, use the API using some buckets, use JS to redirect to a different origin that's also under your control, and now you can use different buckets).

The delay is absolutely necessary for a bunch of security properties. We (@oyiptong and I) should write that up in the security and privacy section.

> 
> > 1. When all the ComputePressureObservers for an origin are removed, the stored scheme is cleared as well.
> 
> Perhaps I'm not sure what you mean by removed, but I don't think this will work because then an attacker could create an observer, observe, remove, and then create another observer with a different scheme.

My understanding is that we're ok with the scheme changing every observation interval (1 second for the focused Document, 10 seconds for all other Documents). When the attacker creates a new observer, the old one gets canceled, so no new events arrive from it. The first event from the new observer will arrive 1 second / 10 seconds after the observer is created. I think this ensures a 1 or 10-second delay between update events from the two observers.

> 
> > The main alternative I've considered is failing ComputePressureObserver creation if the current scheme doesn't match the stored scheme. I dislike that this alternative can "wedge" an origin that's trying to push updated code.
> 
> Oh so I guess this is why you'd want to stop/cancel all observers? I still don't think this is good enough for privacy due to my answer to 4).

WDYT after reading my explanation above? (I acknowledge that if the explanation is acceptable, it needs to make its way into the explainer and spec.)

**Comment by npm1** [comment]
Ok thanks for the explanation! Just one comment still.

> 
> > > 1. When all the ComputePressureObservers for an origin are removed, the stored scheme is cleared as well.
> > 
> > 
> > Perhaps I'm not sure what you mean by removed, but I don't think this will work because then an attacker could create an observer, observe, remove, and then create another observer with a different scheme.
> 
> My understanding is that we're ok with the scheme changing every observation interval (1 second for the focused Document, 10 seconds for all other Documents). When the attacker creates a new observer, the old one gets canceled, so no new events arrive from it. The first event from the new observer will arrive 1 second / 10 seconds after the observer is created. I think this ensures a 1 or 10-second delay between update events from the two observers.

Well I'm not a privacy expert but it's still not obvious to me why this is OK. If the attacker is not doing anything intensive in the page then chances are they are able to get very precise data on the user by using clever buckets (basically zooming in). For instance suppose it reports values 0-100 with 2 buckets. Attacker uses buckets (0,50), (50,100). Suppose that the first observation returns the first bucket. Then the attack cancels that observer and creates a new one with buckets (0,25), (25,100) (since it knows that it's within the (0,50)) for their next query. Either way it gained greater granularity, and at a very fast speed (it's binary search). So I think that this needs to be disallowed unless there are some very strong use cases and the mitigations to this attack are reasonable...

**Comment by kenchris** [comment]
I don't see the major use-case for allowing multiple observers. Especially as a later script injection can create a new observer and take over. It makes more sense that you can only create once in the life cycle of the document and after that creation will fail.

We can still allow reconfiguring the options (like making options part of the observe() call, like other observers), with the same delays as above for applying the new options.

This way it is going to be much harder for the injector/attacker to get hold on the first instance of the observer.

If we are afraid that a site is not using compute pressure but a later injected script might, we could create a permission policy with the default of 'none' (so that only sites that indent to be using compute pressure will be able to)

**Comment by kenchris** [comment]
We still need to handle multiple documents in the same origin, but that makes updating the options complicated as how will that affect existing instances on other documents.

**Comment by yoavweiss** [comment]
> I don't see the major use-case for allowing multiple observers

What about multiple analytics libraries registered on the same page, each interested in observing compute pressure? This is something we have seen in the wild (and which resulted in issues with Resource Timing and its buffer clearing behavior).

**Comment by kenchris** [comment]
I see. I wonder how useful it will be though if they have to have the exact same buckets or if they end up modifying the existing buckets.

**Comment by kenchris** [comment]
With the move to high-level states which removes the ability so create your own buckets, these issues go away so I think we should close this
