### ISSUE TITLE
ComputePressureObserver ownership

### ISSUE THREAD

**Issue by pwnall** [WICG/compute-pressure#3]
Similar IntersectionObserver issue: https://github.com/w3c/IntersectionObserver/issues/64

Our observers are conceptually attached to the document (not a DOM node or other JS object), so there's no natural place to "hang" ownership off of.

Here are the options I see.

1. The observer conceptually hangs off of the Document / global object. Downsides:
    a. If the ComputePressureObserver JS object is garbage-collected, there's no way to stop the observer. It will keep the listeners alive (normal for an EventHandler, afaik) and invoke them until the user navigates away from the page.

2. The observer is owned by the ComputePressureObserver JS object. Downsides:
    a. Garbage collection can be observed by JS (events stop getting dispatched).
    b. Less consistent behavior, probably more difficult for developers to debug.

**Comment by pwnall** [comment]
@npm1 Any thoughts on ComputePressureObserver ownership?

**Comment by npm1** [comment]
I think this could follow a similar pattern to what was decided with `IntersectionObserver`: a `ComputePressureObserver` could be cleared by the user agent once there are no JS references to the object and the observer is not observing. Based on my understanding, it could stop observing when its observing callback is cancelled or when its ExecutionContext is going to be destroyed. So basically there should be a `stop()` or `disconnect()` method.

**Comment by pwnall** [comment]
@npm1 I think you're agreeing with option 1, because you wrote "there are no JS references to the object **and** the observer is not observing". So, if the `ComputePressureObserver` JS object gets garbage collected before `stop()` / `disconnect()` is called on it, the underlying observer is still observing, and will continue to do so until the user navigates to a different page.

Here is a difference vs `IntersectionObserver`  that I thought is significant -- I think that `IntersectionObserver` is set up to observe a DOM subtree, and observing can be stopped by removing the subtree from the document. `ComputePressureObserver` doesn't have an equivalent.

Did I understand your feedback?

**Comment by npm1** [comment]
Yea perhaps I'm agreeing with option 1, but with a simple solution to the downside: pass the observer object to the callback. That way you can always stop the observer even if you no longer have the var from when you created it.

**Comment by kenchris** [comment]
I think there are some other issues here.

1. There doesn't seem to be any need for more than one observer per document. If there were, they you could generate many with different buckets and deduct much more precise values
2. The above means that there should just be one, so we need an accessor instead similar to how wake lock works:

Basically something like

```webidl
[SecureContext]
partial interface Navigator {
  [SameObject] readonly attribute ComputeObserver computeObserver;
};
```

which has its own issues, with how to assign the callback and options. ResizeObserver sets options as part of observe() anyway.

3. When we in the future supports GPUs etc, maybe we don't want to handle those with the same observer (maybe the polling frequency will differ). Or maybe we do? My experience is that for this reason it is best that we instead just notify then changes are available and then the values can be queried from the object itself. Generic Sensors also did this as it avoided GC issues due to exposing the data in the callback (event handler) itself.

**Comment by kenchris** [comment]
The @w3ctag has some recommendation on whether to use events (generic sensor like API) or a callback (observer like pattern):

https://www.w3.org/TR/design-principles/#events-vs-observers

We need to look at this carefully.

It also highlights further differences with ComputePressureObserver:

> Each instance of the Observer class is constructed with a callback, and optionally with some options to customize what should be observed.

Actually only IntersectionObserver takes options as part of the ctor, all others as part of calls to `observe()`

> Instances begin observing specific targets, using a method named observe(), which takes a reference to the target to be observed. The options to customize what should be observed may be provided here instead of to the constructor. The callback provided in the constructor is invoked when something interesting happens to those targets.

We don't have a special target - we don't allow targetting a specific CPU core or similar. We might allow GPU in the future, but observing something specific doesn't work nicely if we only have a singleton. It might make sense to allow `observe` to change the options.

> Callbacks receive change records as arguments. These records contain the details about the interesting thing that happened. Multiple records can be delivered at once.

Yes, all existing observers do that. That might make a lot of sense for us as well, maybe even with timestamp.

> The author may stop observing by calling a method called unobserve() or disconnect() on the Observer instance.

We currently use `unobserve()` - maybe `disconnect()` is better and also makes more sense if we allow changing options on the fly.

Looking at examples:

```webidl
[Exposed=(Window)]
interface ResizeObserver {
    constructor(ResizeObserverCallback callback);
    undefined observe(Element target, optional ResizeObserverOptions options = {});
    undefined unobserve(Element target);
    undefined disconnect();
};
```
I see that you can observe multiple elements and disconnect stops all observations. Now this makes sense thinking about CPU and GPU etc

```webidl
    enum ComputePressureTarget { "cpu", "gpu" };

    undefined observe(ComputePressureTarget target, optional ComputePressureObserverOptions options = {});
    undefined unobserve(ComputePressureTarget target);
    undefined disconnect();
};
```

> Optionally, a method may be provided to immediately return records for all observed-but-not-yet-delivered occurrences.

This is the `takeRecords()` method other observers support. With batching that makes sense supporting

**Comment by kenchris** [comment]
I found another Observer in the web platform that is very similar to what we want:

https://www.w3.org/TR/performance-timeline/#idl-index

That is in many ways similar to what we want and probably what we should base this on.

**Comment by kenchris** [comment]
A small set of observations before we start thinking about this

In alignment with other observers on the platform:

- `disconnect()` now exists
- the observer is passed to the callback

**Comment by kenchris** [comment]
I guess we the above we could do the same as Intersection Observer:

IntersectionObserverLifetime
An IntersectionObserver will remain alive until both of these conditions hold:

* There are no scripting references to the observer.
* The observer is not observing any targets.

An IntersectionObserver will continue observing a target until either the observer’s unobserve() method is called with the target as argument; or the observer’s disconnect() is called.
