### ISSUE TITLE
System shows 100% consumption but browser CPU Utilization doesnt 

### ISSUE THREAD

**Issue by altanai** [WICG/compute-pressure#35]
I am running an experiment to measure the client-side CPU load under different video conferencing architectures ( mesh, mixer, SFU etc ). I have set up this on chrome beta with fake streams and have no other program running on this machine( that take significant more power than idle). 
When I see my CPU utilization spiking to 100% on large scale video conferences on my system performance monitor, I do not see 100% CPU utilization on the compute API reports. Is it designed to never go above 75%?  or I am mssing something ?

For example I have never seen any value go above 75% CPU Utilization and 75 % CPU speed.
1.943	0.75	0.75
1.08	0.75	0.75
1.923	0.75	0.75
2.007	0.75	0.75
2.071	0.75	0.75

Even though CPU is heated immesely and shows ~99% utilization on all cores.
My system's has Intel® Core™ i7-7500U CPU @ 2.70GHz × 4.

**Comment by kenchris** [comment]
Hi there,

Could you add a bit more info, like I assume this is on Linux. What buckets are you using? Chrome limits the amount of buckets so maybe there is no bucket covering >0.75

**Comment by arskama** [comment]
Hi,

@altanai, I would assume that your last bucket thresholds are 0.5 and 1.0?
Which would make sense since the bucketing makes it so that the value will fall in the middle value of the bucket.
So if you have 0.5 and 1.0, and you reach 1.0 (100%), you will get 0.75.

This quantization is necessary to avoid fingerprinting.

Am I correct?

**Comment by kenchris** [comment]
This is correct @arskama - if there is a bucket between 0.5 and 1.0 the middle value (0.75) is reported. We are moving away from this API thought.

As things work as expected I am going to close this issue
