### ISSUE TITLE
How to handle user permission

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#44]
From @beaufortfrancois:

```
They do not tell you anything, however, about whether that API is actually connected to a
real [=platform collector=], whether the [=platform collector=] is collecting real telemetry
readings, or whether the user is going to allow you to access it.
```

> I didn't see in the spec where user could not allow it.

 
True, we haven't looked into whether we want to guard this behind a permission and where that should be done. Let's discuss that here

**Comment by beaufortfrancois** [comment]
Why is this closed? `"whether the user is going to allow you to access it"` is still in the spec and there are no permissions yet: https://wicg.github.io/compute-pressure/#:~:text=whether%20the%20user%20is%20going%20to%20allow%20you%20to%20access%20it

**Comment by kenchris** [comment]
Then try reloading :-)

https://wicg.github.io/compute-pressure/#permissions-and-user-prompts
https://wicg.github.io/compute-pressure/#dom-computepressureobserver-requestpermission
https://wicg.github.io/compute-pressure/#the-observe-method

**Comment by beaufortfrancois** [comment]
I see now. It would have been nice to link to https://github.com/WICG/compute-pressure/pull/58 ;)
Thank you!

**Comment by kenchris** [comment]
Yes, I normally do that, but somehow forgot
