### ISSUE TITLE
Throw NotAllowedError when permission is prompt

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/compute-pressure#59]
According to the spec text below, `ComputePressureObserver` `observe()` does not throw when permission is `"prompt"`. 
https://github.com/WICG/compute-pressure/blob/75052b4fd3f1ce425d61fe85d14b1b3d4ff59408/index.html#L379

I believe it should be ` If |permissionState| is not [=permission/granted=], throw {{NotAllowedError}}.` as 
https://www.w3.org/TR/permissions/#dfn-prompt also exists.

What do you think @kenchris?

**Comment by kenchris** [comment]
I believe query can only return grant or deny but I need to check

**Comment by beaufortfrancois** [comment]
Example suggests "prompt" is valid: https://www.w3.org/TR/permissions/#example-using-state-attribute
