### ISSUE TITLE
Quantization clarification - how are threshold values handled?

### ISSUE THREAD

**Issue by pwnall** [WICG/compute-pressure#6]
How should implementations handle values that exactly equal the quantization thresholds?

For example, the CPU utilization thresholds [0.2, 0.5, 0.8] will create the intervals [0, 0.2], [0.2, 0.5], [0.5, 0.8] and [0.8, 1]. If the measured CPU utilization is exactly 0.5, would that be quantized to 0.35 (for the interval [0.2, 0.5]) or 0.65 (for the interval [0.5, 0.8])?

(Yes, the current explainer and samples are intentionally vague, because I didn't have a good answer.)

**Comment by pwnall** [comment]
Some options I can think of

* Either bucket may be reported (status quo). In this case, I think we should recommend developers to nudge their thresholds to get clear behavior here -- in our example, better thresholds would be [0.20001, 0.50001, 0.79999]
* Arbitrary simple policy -- always quantizing to the higher / lower bucket.
* Arbitrary but more complex policy similar to rounding -- threshold values < 0.5 get quantized to the lower bucket, and threshold values >= 0.5 get quantized to the higher bucket.
* Arbitrary but more complex policy based on respecting the JS we want authors to write -- the first threshold gets quantized to the lower bucket, all other thresholds get quantized to higher buckets.

The last option deserves more explanation. Since we report 0.1 for the range [0, 0.2] and 0.9 for the range [0.8, 1.0], we want authors to write conditionals like `if (cpuUtilization < 0.2)` and `if (cpuUtilization > 0.8)`. The last option makes quantizing match these conditionals for the extreme buckets.

**Comment by kenchris** [comment]
Closing as this has become irrelevant with the new high-level states approach
