### ISSUE TITLE
Unclear how a sample makes its way from a platform collector to a ComputePressureUpdateCallback

### ISSUE THREAD

**Issue by rakuco** [WICG/compute-pressure#65]
https://wicg.github.io/compute-pressure/#platform-primitives says

> When a sample is obtained from the [platform collector](https://wicg.github.io/compute-pressure/#dfn-platform-collector), the [user agent](https://wicg.github.io/compute-pressure/#dfn-user-agent) MUST run the [8.6.4 Notify Compute Pressure Observers](https://wicg.github.io/compute-pressure/#notify-observers) algorithm a per the [8.6 Processing Model](https://wicg.github.io/compute-pressure/#processing-model)

That looks like the wrong algorithm though, as the process through which the sample collected by the platform is added to a `ComputePressureRecord`, how this `ComputePressureRecord` is created and how the relevant `ComputePressureObserver` instances are selected for a given target type are not clear.

**Comment by rakuco** [comment]
I'm reopening this one after looking at 4e14fb7d1a21cacd2a37eb10d1413e87bf2070c9 to list a few things that still need to improvement:
- https://wicg.github.io/compute-pressure/#queue-a-computepressurerecord:
  - [ ] The variables `target` and `data` should have a type just like `record`. I think this applies to some other algorithms as well.
  - [ ] `observer` is not being defined anywhere before it is used in step 2.
  - [ ] You could check whether the document is fully active before creating a new `ComputePressureRecord` to avoid having to discard it immediately after creation (I'm guessing if the document is not fully active you don't want to manipulate `[[QueuedRecords]]`).

**Comment by rakuco** [comment]
Oops, I don't have permission to reopen the issue :-)

**Comment by kenchris** [comment]
As data is implementation-defined, I am not really sure what type to use, but for the target I can use the enum.
