### ISSUE TITLE
Explain trimming the quantization scheme

### ISSUE THREAD

**Issue by pwnall** [WICG/compute-pressure#7]
The current API design has a (currently very subtle) avenue for allowing user agents to determine how much entropy they're willing to expose with this feature.

Quantization schemes are expressed as arrays. Web authors are expected to list value thresholds in order of relative importance, and user agents may choose to ignore some of the thresholds.

For example, Chrome's prototype implementation allows 3 thresholds for CPU utilization. A quantization scheme of `[0.5, 0.8, 0.3, 0.9, 0.2]` will be reduced to `[0.3, 0.5, 0.8]` (the sorted version of `[0.5, 0.8, 0.3]`).

**Comment by kenchris** [comment]
Chrome's current implementation allows for 5 buckets in total across utilization (3) and frequency (2), but we are now moving to a high-level states approach with 4 states, so going to close this
