### ISSUE TITLE
Integration with picture-in-picture

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#83]
To avoid cross origin user tracking, many specs restrict features to active focuses documents (example Generic Sensors).

But for compute pressure, one of the core use-cases is actually to know the CPU pressure while writing minutes (summary of meeting notes) to make sure the typing experience is smooth, and the video streams and effects do not negatively affect the minute taking. 

But during minute taking, it is quite common that the web site/app using compute pressure is not actually focused, as the word processing app is

This will require hooks in other specs and we probably need something like a initiator-of-still-active-picture-in-picture-session

@beaufortfrancois @riju @fideltian

**Comment by beaufortfrancois** [comment]
Do you need anything from me?

**Comment by kenchris** [comment]
@beaufortfrancois Probably yes, as currently spec'ed there can be multiple origins and site instances showing picture-in-picture at the same time though I don't think anyone actually implemented that.

Originally I had a patch that was looking at the pictureInPictureElement to see if it was set or not, but some spec language to have a initiators-of-still-active-picture-in-picture-session array in the picture-in-picture spec would let me hook into it by checking if that contained my current document.

I am open to other options but that fits best with the way @eladalon1983 suggested we handle screen share

**Comment by kenchris** [comment]
This is now integrated in the spec, thanks for the help
