### ISSUE TITLE
Don't pass in options in the callback

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#88]
No other Observer spec does this, except PerformanceObserver, but that is really not an "option" as its basically additional data given to the callback and not options as supplied by the developer

**Comment by arskama** [comment]
I m ok with removing it.

The initial idea behind that was to most probably inform the developer on what buckets have been selected, in case the bucket borders were more than the accepted one. for example max bucket is 3, and developer would request 5 buckets.
At the callback we could get then what were the bucket generated by the user-agent.

It is not really relevant anymore.

**Comment by kenchris** [comment]
Done now
