### ISSUE TITLE
Clarify better what supported means with regard to the ComputePressureSource enum

### ISSUE THREAD

**Issue by arskama** [WICG/compute-pressure#91]
Now that we use ComputePressureSource as type instead of DomString, we need to adapt the error return to TypeError.

**Comment by kenchris** [comment]
Maybe we don't

If people call it with a string not in the enum, it will fail with a TypeError which is normal, but if a platform does implement a version of the spec with, say "cpu" and "gpu" as part of the enum, then they might still not support "gpu", but WebIDL will not let "gpu" throw TypeError, and I think NotSupportedError makes more sense in this case.

We might want to add some text about what "supported" means here and better clarify. I can look at that next week
