### ISSUE TITLE
Modernize spec text

### ISSUE THREAD

**Issue by inexorabletash** [WICG/compute-pressure#96]
The spec is written with an obsolete style for method and attribute algorithms, e.g.:

> The [observe](https://wicg.github.io/compute-pressure/#dom-computepressureobserver-observe)() method, when invoked, MUST run the following step, given the arguments source:

> When [supportedSources](https://wicg.github.io/compute-pressure/#dom-computepressureobserver-supportedsources)'s attribute getter is called, MUST run the following steps:

The more compact modern way is:

> The _**observe(source)**_ method steps are:

> The _**supportedSources**_ getter's steps are:

**Comment by inexorabletash** [comment]
Web IDL actually gives the phrases to use e.g. in:

https://webidl.spec.whatwg.org/#getter-steps
https://webidl.spec.whatwg.org/#method-steps
https://webidl.spec.whatwg.org/#constructor-steps

(discussion leading to this in https://github.com/whatwg/webidl/issues/730 / https://github.com/whatwg/webidl/pull/882)

Web IDL itself gives plenty of examples. I've applied that to my specs as well, e.g. [IndexedDB](https://w3c.github.io/IndexedDB/), [Web Locks](https://w3c.github.io/web-locks/)

**Comment by kenchris** [comment]
There is a PR for this now, maybe there are better ways of doing this with respec @marcoscaceres ?
